In [1]:
import tensorflow as tf
import numpy as np

# Pick an easy example and do it in Numpy

In [2]:
f1 = np.array([[1.,2.,3.],[4.,5.,6.]])
f1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [3]:
f2 = np.array([[7.,8.,9.],[10.,11.,12.]])
f2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [4]:
np.sum(f1*f2)

217.0

In [5]:
np.matmul(f1.flatten(),np.transpose(f2.flatten()))

217.0

In [6]:
F = np.array([f1,f2])
print F.shape
F

(2, 2, 3)


array([[[  1.,   2.,   3.],
        [  4.,   5.,   6.]],

       [[  7.,   8.,   9.],
        [ 10.,  11.,  12.]]])

In [7]:
np.sum(np.square(f2.flatten()))

559.0

In [8]:
F_flat = F.reshape(F.shape[0],F.shape[1]*F.shape[2])
F_flat

array([[  1.,   2.,   3.,   4.,   5.,   6.],
       [  7.,   8.,   9.,  10.,  11.,  12.]])

In [9]:
np.matmul(F_flat,F_flat.T)

array([[  91.,  217.],
       [ 217.,  559.]])

# TensorFlow

In [10]:
def Gram_Matrix(F_batch):
    F = F_batch[0]
    s = tf.shape(F)
    F_flat = tf.reshape(F,shape=(s[0],s[1]*s[2]))
    G = tf.matmul(F_flat,tf.transpose(F_flat))
    return G

In [11]:
g = tf.Graph()
with g.as_default():
    F = tf.placeholder(tf.float32)
    G = Gram_Matrix(F)

In [14]:
sess = tf.Session(graph = g)
writer = tf.train.SummaryWriter('./logs/',graph=g)

F_in = np.array([[f1,f2]])
fd = {F : F_in}
sess.run(G,feed_dict=fd)

array([[  91.,  217.],
       [ 217.,  559.]], dtype=float32)